
sim:
#   xml_path: "configs/sim_replay/mjcfs/ai2robotics_bot2/Bot2_ZPF_L2Fgripper_R2Fgripper_A_description_with_sites.xml"  # 仿真模型路径
  xml_path: "configs/sim_replay/mjcfs/ai2robotics_bot2/bot2_mujoco.xml"  # 仿真模型路径
  module_file: config.sim_replay.AI2_Alphabot_2
  function: get_mjcf_gripper_joint_data

  joints:
    ZPF_left_Joint1: left_arm_joint_1_rad
    ZPF_left_Joint2: left_arm_joint_2_rad
    ZPF_left_Joint3: left_arm_joint_3_rad
    ZPF_left_Joint4: left_arm_joint_4_rad
    ZPF_left_Joint5: left_arm_joint_5_rad
    ZPF_left_Joint6: left_arm_joint_6_rad
    ZPF_left_Joint7: left_arm_joint_7_rad
    ZPF_right_Joint1: right_arm_joint_1_rad
    ZPF_right_Joint1: right_arm_joint_2_rad
    ZPF_right_Joint3: right_arm_joint_3_rad
    ZPF_right_Joint4: right_arm_joint_4_rad
    ZPF_right_Joint5: right_arm_joint_5_rad
    ZPF_right_Joint6: right_arm_joint_6_rad
    ZPF_right_Joint7: right_arm_joint_7_rad
    2FEG_l_Joint1: fl_joint7
    2FEG_l_Joint2: fl_joint7
    2FEG_l_Joint4: fl_joint8
    2FEG_l_Joint3: fl_joint8
    2FEG_r_Joint1: fr_joint7
    2FEG_r_Joint2: fr_joint7
    2FEG_r_Joint4: fr_joint8
    2FEG_r_Joint3: fr_joint8
                                          
  # 物理世界的限制 (MuJoCo 中的实际行程, 单位: 米或弧度)
  gripper_config:
    gripper_name:
      - left_gripper_open_scale
      - right_gripper_open_scale
    gripper_joint_max: 0.82  # 物理完全张开的宽度
    gripper_joint_min: 0.0   # 物理完全闭合的宽度
    gripper: False

  camera:   # 相机参数可以从 tools/sim_replay/get_camara.py 中获取
    lookat_x: 0.487  
    lookat_y: -0.000
    lookat_z: 0.824
    distance: 2.000
    azimuth: -0.250
    elevation: -81.250

default_version:
  gripper_config:
    gripper_value_open: 1.0  # 数据中表示"开"的值
    gripper_value_close: 0.0 # 数据中表示"关"的值


show_plt: 
  - 
    - left_gripper_open_scale
  - 
    - right_gripper_open_scale