sim:
  xml_path: "configs/sim_replay/mjcfs/galaxea_r1_lite/mmp_revB_invconfig_upright_a1x_with_sites.xml"
  module_file: config.sim_replay.galaxea
  function: get_mjcf_gripper_joint_data

  joints:
    left_arm_joint1: leader_left_arm_joint_1_rad.pos
    left_arm_joint2: leader_left_arm_joint_2_rad.pos
    left_arm_joint3: leader_left_arm_joint_3_rad.pos
    left_arm_joint4: leader_left_arm_joint_4_rad.pos
    left_arm_joint5: leader_left_arm_joint_5_rad.pos
    left_arm_joint6: leader_left_arm_joint_6_rad.pos
    right_arm_joint1: leader_right_arm_joint_1_rad.pos
    right_arm_joint2: leader_right_arm_joint_2_rad.pos
    right_arm_joint3: leader_right_arm_joint_3_rad.pos
    right_arm_joint4: leader_right_arm_joint_4_rad.pos
    right_arm_joint5: leader_right_arm_joint_5_rad.pos
    right_arm_joint6: leader_right_arm_joint_6_rad.pos
    left_gripper_finger_joint1: fl_joint7
    left_gripper_finger_joint2: fl_joint8
    right_gripper_finger_joint1: fr_joint7
    right_gripper_finger_joint2: fr_joint8

  gripper_config:
    gripper_name:
      - leader_left_gripper_degree_mm.pos
      - leader_right_gripper_degree_mm.pos
    gripper_joint_max: 0.05
    gripper_joint_min: 0.0
    gripper: True

  camera:
    lookat_x: 0.487
    lookat_y: 0.0
    lookat_z: 0.824
    distance: 2.0
    azimuth: -0.25
    elevation: -81.25

default_version:
  gripper_config:
    gripper_value_open: 100.0
    gripper_value_close: 0.0
