# postgresql_config.yaml
postgresql:
  user: "robocoin_server"        # 替换为你的数据库用户名
  password: "7sK9$pR2!g"    # 替换为你的数据库密码
  host: "localhost"            # 数据库主机地址
  port: 5432                  # 数据库端口
  database: "robocoin_datasets_test"  # 数据库名
  # 可选：添加其他连接参数
  pool_size: 10
  max_overflow: 20
  echo: false